Vagrant.configure("2") do |config|
  config.vbguest.auto_update = false
  
  config.vm.define "debian" do |debian|
    debian.vm.box = "debian/jessie64"
    debian.vm.provider "virtualbox" do |v|
      v.cpus = 2
      v.memory = 2048
    end
    debian.vm.synced_folder ".", "/vagrant", disabled: true
  end
end
