Vagrant.configure("2") do |config|
  config.vbguest.auto_update = false
  
  config.vm.define "fedora" do |fedora|
    fedora.vm.box = "fedora/27-cloud-base"
    fedora.vm.provider "virtualbox" do |v|
      v.cpus = 2
      v.memory = 2048
    end
    fedora.vm.synced_folder ".", "/vagrant", disabled: true
  end
end
