Vagrant.configure("2") do |config|
  config.vm.define "system1" do |system1|
    system1.vm.box = "fedora/25-cloud-base"
  end

  config.vm.define "system2" do |system2|
    system2.vm.box = "fedora/25-cloud-base"
  end

  config.vm.provision "shell" do |s|
    s.inline = "dnf -y install python python2-dnf libselinux-python"
  end

  config.vm.provision "ansible" do |ansible|
    ansible.playbook = "playbook.yml"
    ansible.sudo = true
  end
end
