Vagrant.configure("2") do |config|
  config.vbguest.auto_update = false
  
  config.vm.define "centos" do |centos|
    centos.vm.box = "centos/7"
    centos.vm.provider "virtualbox" do |v|
      v.cpus = 2
      v.memory = 2048
    end
    centos.vm.synced_folder ".", "/vagrant", disabled: true
  end
  
  config.vm.define "fedora" do |fedora|
    fedora.vm.box = "fedora/25-cloud-base"
    fedora.vm.provider "virtualbox" do |v|
      v.cpus = 2
      v.memory = 2048
    end
    fedora.vm.provision "shell" do |s|
      s.inline = "dnf -y install python python2-dnf libselinux-python"
    end
    fedora.vm.synced_folder ".", "/vagrant", disabled: true
  end
  
  config.vm.define "debian" do |debian|
    debian.vm.box = "debian/jessie64"
    debian.vm.provider "virtualbox" do |v|
      v.cpus = 2
      v.memory = 2048
    end
    debian.vm.provision "ansible" do |a|
      a.limit = "all"
      a.playbook = "site.yml"
    end
    debian.vm.synced_folder ".", "/vagrant", disabled: true
  end
end
